---

- name: Create lb-mon
  tags:
    - create_lb_mon
    - uri
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/lbmonitor"
    method: POST
    status_code: 201,409
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"lbmonitor": {{ item | to_json }} }'
  with_items: "{{ lbmonitors.lbmonitor }}"
  register: create_lb_mon_result
  when: lbmonitors.lbmonitor is defined

