---

- name: Create Policy Expresions
  tags:
    - create_policy_expressions
    - create_policies
    - uri
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/policyexpression"
    method: POST
    status_code: 200,201,409,599
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"policyexpression": {{ item | to_json }} }'
  register: create_policy_expressions
  with_items: "{{ policyexpressions.policyexpression }}"
  when: policyexpressions.policyexpression is defined


- name: Create Transfrom Policies
  tags:
    - create_policies
    - create_transform_policies
    - uri
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/transformpolicy"
    method: POST
    status_code: 200,201,409,599
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"transformpolicy": {{ item }} }'
  register: create_transformpolicy
  with_items: "{{ policies.transformpolicy }}"
  when: policies.transformpolicy is defined

- name: Create Responder Policies 
  tags:
    - create_policies
    - create_responder_policies
    - uri
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/responderpolicy"
    method: POST
    status_code: 200,201,409,599
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"responderpolicy": {{ item }} }'
  register: create_responderpolicy
  with_items: "{{ policies.responderpolicy }}"
  when: policies.responderpolicy is defined

- name: Create Rewrite Policies
  tags:
    - create_policies
    - create_rewrite_policies
    - uri
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/rewritepolicy"
    method: POST
    status_code: 200,201,409,599
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"rewritepolicy": {{ item | to_json }} }'
  register: create_rewritepolicy
  with_items: "{{ policies.rewritepolicy }}"
  when: policies.rewritepolicy is defined


- name: Create CS Policies
  tags:
    - create_policies
    - create_cs_policies
    - uri
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/cspolicy"
    method: POST
    status_code: 200,201,409,599
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"cspolicy": {{ item | to_json }} }'
  register: create_cspolicy
  with_items: "{{ policies.cspolicy }}"
  when: policies.cspolicy is defined

