---

- name: Create policypatset
  delegate_to: localhost
  tags:
    - create_policy_patset
    - uri
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/policypatset/{{ item }}"
    method: POST
    status_code: 200,201,409
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"policypatset":{"name":"{{ item }}"} }'
  register: create_policy_patset
  with_items: "{{ patsets.patset }}"
  when: patsets.patset is defined


- name: Bind URLs to policypatset
  delegate_to: localhost
  tags:
    - bind_patsets
    - uri
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/policypatset_pattern_binding"
    method: PUT
    status_code: 200,599
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"policypatset_pattern_binding": {{ item | to_json }} }'
  register: bind_patsets
  with_items: "{{ patsets.policypatset_pattern_binding }}"
  ignore_errors: True
  when: patsets.policypatset_pattern_binding is defined

