---

#- name: Create LB vserver
#  tags:
#    - create_lb_vserver 
#  delegate_to: localhost
#  netscaler_lb_vserver:
#    nsip: "{{ ns_ip }}"
#    validate_certs: no
#    nitro_user: "{{ ns_user }}"
#    nitro_pass: "{{ ns_pass }}"
#    state: present

#    name: "{{ item.key }}"
#    servicetype: "{{ item.value.servicetype }}"
#    lbmethod: "{{ item.value.lbmethod | upper }}"
#    listenpolicy: "{{ item.value.listenpolicy }}"
#    ipv46: "{{ item.value.ipv46 }}"
#    persistencetype: "{{ item.value.persistencetype }}"
#    port: '{{ item.value.port }}'
#    clttimeout: "{{ item.value.clttimeout }}"

#    servicegroupbindings:
#      - servicegroupname: "{{ bindings.lbmons.servicegroupname }}"
#  register: create_lb_vserver
#  with_dict: "{{ lbvservers }}"




- name: Create backup lbvserver (uri)
  tags:
    - create_lbvserver_uri
    - uri
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/lbvserver"
    method: POST
    status_code: 200,201,409
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"lbvserver": {{ item | to_json }} }'
  with_items: "{{ lbvservers.backuplbvserver }}"
  register: create_lbvserver_uri
  when: lbvservers.backuplbvserver is defined



- name: Create lbvserver (uri)
  tags:
    - create_lbvserver_uri
    - uri
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/lbvserver"
    method: POST
    status_code: 200,201,409
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"lbvserver": {{ item | to_json }} }'
  with_items: "{{ lbvservers.lbvserver }}"
  register: create_lbvserver_uri
  ignore_errors: True


- name: Bind lb vserver to serviceGroup (uri)
  tags:
    - create_lbvserver_uri
    - bind_lbvserver_uri
    - uri
    - module
  delegate_to: localhost
  uri:
    url: "http://{{ ns_ip }}/nitro/v1/config/lbvserver_servicegroup_binding"
    method: POST
    status_code: 201, 599, 409
    return_content: yes
    headers:
      X-NITRO-USER: "{{ ns_user }}"
      X-NITRO-PASS: "{{ ns_pass }}"
    body_format: json
    body: '{"lbvserver_servicegroup_binding": {{ item | to_json }} }'
  with_items: "{{ lbvservers.lbvserver_binding.lbvserver_servicegroup_binding }}"
  register: bind_lbmon_uri
  ignore_errors: True
